Added sonar dependency

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,7 +8,7 @@ on:
 
 jobs:
   build-deploy:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted # Use the self-hosted runner
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -32,13 +32,17 @@ jobs:
       - name: Build with Maven
         run: mvn clean package -DskipTests
 
+      - name: Test SonarQube connectivity
+        run: |
+          curl -v -f http://192.168.2.189:30000 || curl -v -f http://localhost:9000 || echo "Failed to reach SonarQube"
+
       - name: Run SonarQube analysis
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          mvn sonar:sonar \
+          mvn sonar:sonar -X \
             -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
-            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
+            -Dsonar.host.url=http://192.168.2.189:30000 \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
       - name: Run tests
@@ -61,8 +65,8 @@ jobs:
             -t ${{ secrets.DOCKERHUB_USERNAME }}/approbation-backend:latest \
             --push .
 
-      - name: Checkout k8s-manifests repository
-        uses: actions/checkout@v4
+      - name: Checkout k8s-manifests repository
+        uses: actionsCheckout@v4
         with:
           repository: SeifeddineABIDI/k8s-manifests
           path: manifests
